version: "3.7"

x-application: &application
  image: e-petitions/ruby
  build: docker/ruby
  environment:
    - DATABASE_URL=postgres://postgres:ZW4IvOPrXcbp2hyp@postgres:5432
    - MEMCACHE_SERVERS=memcached:11211
    - SMTP_HOST=mailcatcher
    - SMTP_PORT=1025
    - SPROCKETS_CACHE=/cache
    - PIDFILE=/tmp/pids/server.pid
  volumes:
    - .:/app
    - bundle:/bundle
    - cache:/cache
    - node_modules:/app/node_modules
  tmpfs:
    - /tmp/pids/
  depends_on:
    - postgres
    - mailcatcher
    - memcached

services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ZW4IvOPrXcbp2hyp
      - POSTGRES_DB=postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  mailcatcher:
    image: e-petitions/mailcatcher
    build: docker/mailcatcher
    expose:
      - "1025"
    ports:
      - "127.0.0.1:1080:1080"

  memcached:
    image: memcached:1.5
    expose:
      - "11121"

  web:
    <<: *application
    command: [
      "rails", "server",
      "-b", "0.0.0.0",
      "-p", "3000"
    ]
    ports:
      - "127.0.0.1:3000:3000"
    stdin_open: true
    tty: true

  worker:
    <<: *application
    command: [
      "bin/delayed_job", "start",
      "-p", "worker",
      "--min-priority", "10",
      "--daemon_options", "-t"
    ]

  counter:
    <<: *application
    command: [
      "bin/delayed_job", "start",
      "-p", "counter",
      "--max-priority", "5",
      "--daemon_options", "-t"
    ]

volumes:
  bundle:
  db:
  cache:
  node_modules:
